name: Laravel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install composer dependencies
      run: |
        composer update --no-scripts

    - name: Prepare Laravel Application
      run: |
        php -r "file_exists('.env') || copy('.env.ci', '.env');"
        php artisan key:generate
    - name: Migrate
      run: php artisan migrate
    - name: Seed
      run: php artisan db:seed
    - name: Passport install
      run: php artisan passport:install
    - name: Route list
      run: php artisan route:list
    - name: PHP optimize
      run: php artisan optimize
    - name: Run Testsuite
      run: |
        php artisan migrate:refresh
        vendor/bin/phpunit tests/
